### ISSUE TITLE
Bug about language

### ISSUE THREAD

**Issue by heliqx** [my-Anki/Beautify-Anki#19]
Looks great and I indeed like it but here some problem , When I set language to Chinese , It told me this: 

Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-28 21:45:05

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 446, in handler
  File "aqt\reviewer.py", line 542, in _onTypedAnswer
  File "aqt\reviewer.py", line 245, in _showAnswer
  File "aqt\reviewer.py", line 600, in _showEaseButtons
  File "<D:\Anki\Anki\decorator.pyc:decorator-gen-24>", line 2, in _answerButtons
  File "lib\site-packages\anki\hooks.py", line 666, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 658, in repl
  File "C:\Users\11540\AppData\Roaming\Anki2\addons21\1150874988\reviewer.py", line 122, in answerButtons
    buf += but(ease, label)
  File "C:\Users\11540\AppData\Roaming\Anki2\addons21\1150874988\reviewer.py", line 112, in but
    color,
UnboundLocalError: local variable 'color' referenced before assignment

I hope next update can fix this bug，thanks

**Comment by ShoroukAziz** [comment]
Hello,
That's a known issue and it's fixed in the coming update
