### ISSUE TITLE
Won't Enable in 2.32

### ISSUE THREAD

**Issue by keithcdodd** [my-Anki/Beautify-Anki#38]
Hello, oddly in the newest 2.32 this addon won't even be enabled for me. If I try to toggle it on, it stays off. Other addons can be toggled appropriately.

**Comment by spartandrew18** [comment]
[v0.3.2.zip](https://github.com/my-Anki/Beautify-Anki/files/5136828/v0.3.2.zip)

**Comment by cereska** [comment]
Also facing the same issue, the addon is not compatible with Anki 2.1.30+.
I'd be really  grateful for an update, as I really love this addon, Anki now feels so weird without it ;)

**Comment by davzaman** [comment]
If you want the fix now you can go to [releases](https://github.com/my-Anki/Beautify-Anki/releases) and scroll down to "Assets" and download the source code zip.
![image](https://user-images.githubusercontent.com/5055644/92859863-74ef8480-f3ac-11ea-85f1-96203e9e585a.png)

Unzip it, and rename the folder to `Beautify-Anki`. Go to Anki and open up the add-on window. Click on any of your add-ons and click "View Files". It will take you to the folder where you have the add-ons saved. Move the `Beautify-Anki` folder here and restart Anki and it should work.

Though there are some issues I noticed: 
1. It eats up a LOT of CPU it was at 99% while it was open.
2. Some blocks  on the page were shaking non-stop no matter what I did.

**Comment by palosbuenos** [comment]
Using Latest Mac Anki + Latest Beautify-Anki 0.3.0

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-11 07:20:48
Add-ons possibly involved: ⁨Beautify-Anki⁩

Traceback (most recent call last):
  File "aqt/main.py", line 521, in loadCollection
  File "aqt/main.py", line 661, in moveToState
  File "aqt/main.py", line 668, in _deckBrowserState
  File "aqt/deckbrowser.py", line 58, in show
  File "aqt/deckbrowser.py", line 115, in _renderPage
  File "aqt/deckbrowser.py", line 124, in __renderPage
  File "aqt/webview.py", line 378, in stdHtml
  File "aqt/gui_hooks.py", line 2917, in __call__
  File "/Users/Paul/Library/Application Support/Anki2/addons21/Beautify-Anki/__init__.py", line 80, in on_webview_will_set_content
    web_content.css.remove("deckbrowser.css")
ValueError: list.remove(x): x not in list

**Comment by cereska** [comment]
@davzaman 

Yeah all the decks and sub-decks are "shaking" for me too, so annoying. The button text & icons don't fit inside. Gotta wait for official release...

**Comment by ShoroukAziz** [comment]
Try this version please and let me know if you're still having proplems
https://github.com/my-Anki/Beautify-Anki/releases/tag/v.0.3.2

**Comment by armankj** [comment]
> the decks in the menu are shaking, when it does this the CPU skyrockets. if i select a specific deck this problem goes away.

Exact same problem here, the whole menu is shaking non-stop. Any solution yet?
