### ISSUE TITLE
Problem when I start anki

### ISSUE THREAD

**Issue by ebanDev** [my-Anki/Beautify-Anki#49]
**Before posting, please verify that you've done the following** 
* [x] read the ["before you install instructions"](https://beautify-anki.shorouk.dev/before-install) and disabled all the known conflicted add-ons.
* [x] You've looked through previous issues to see if someone else had the same problem.

**Describe the bug**

**Screenshots**
When I start anki I have this error message 

```
Erreur
￼ Une erreur est survenue. Veuillez démarrer Anki en maintenant la touche majuscule enfoncée, ce qui désactivera temporairement les greffons que vous avez installés. ￼ Si le problème ne survient que lorsque les greffons sont activés, veuillez utiliser le menu Outils > Greffons afin de désactiver certains greffons. Redémarrez Anki jusqu’à ce que vous découvriez le greffon qui cause le problème. ￼ Une fois ce greffon découvert, merci de signaler le problème sur le site de support du greffon.￼ ￼ Information de débogage :
Anki 2.1.38 (355e4cd5) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-01-02 21:21:12
Greffons possiblement impliqués : ⁨BeautifyAnki⁩

Traceback (most recent call last):
  File "aqt/main.py", line 503, in loadCollection
  File "aqt/main.py", line 635, in moveToState
  File "aqt/main.py", line 642, in _deckBrowserState
  File "aqt/deckbrowser.py", line 56, in show
  File "aqt/deckbrowser.py", line 113, in _renderPage
  File "aqt/deckbrowser.py", line 123, in __renderPage
  File "aqt/webview.py", line 446, in stdHtml
  File "aqt/hooks_gen.py", line 3184, in __call__
  File "/home/eban/.local/share/Anki2/addons21/BeautifyAnki/__init__.py", line 80, in on_webview_will_set_content
    web_content.css.remove("deckbrowser.css")
ValueError: list.remove(x): x not in list
```

**Contex (please complete the following information):**
 - OS: [Fedora]
 - Anki Version [e.g. 2.1.38]
 - 
**Additional context**
In your Anki 
go to help > About > Copy Debug Log and paste it between the following backticks 

```
    
    Anki 2.1.38 (355e4cd5) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
    Platform: Linux
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2021-01-02 21:21:12
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['BeautifyAnki', 0, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Review Heatmap ['review_heatmap', 2020-04-30T15:23, 'None', '']
    The KING of Button Add-ons ['374005964', 2020-04-18T00:33, 'None', '']
```

**Comment by coco1602** [comment]
I have the same issue.

**Comment by superbat85** [comment]
I have the same issue, anyone have any idea what could be the problem?
