### ISSUE TITLE
Compatibility with rememorize buttons

### ISSUE THREAD

**Issue by galantra** [my-Anki/Beautify-Anki#6]
Thanks for creating this add-on. I believe it'll make more people inclined to using Anki, and therefore increase study efficency and decrease stress.

Before this add-on, I used [rememorize_btn](https://github.com/lovac42/ReMemorizeButtons/) in combination with [Minimal Flat Big Buttons (compatible with ReMemorize Buttons)](https://ankiweb.net/shared/info/1042429613).

_Beautify_ is apparently not compatible:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-18 16:04:47

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 446, in handler
  File "aqt\reviewer.py", line 542, in _onTypedAnswer
  File "<C:\Users\user\PortableApps\AnkiPortable\Anki\decorator.pyc:decorator-gen-60>", line 2, in _showAnswer
  File "lib\site-packages\anki\hooks.py", line 666, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 663, in repl
  File "C:\Users\user\PortableApps\AnkiPortable\Anki2\addons21\1374772155\main.py", line 233, in onShowAnswer
    return _old(self)
  File "aqt\reviewer.py", line 245, in _showAnswer
  File "aqt\reviewer.py", line 600, in _showEaseButtons
  File "<C:\Users\user\PortableApps\AnkiPortable\Anki\decorator.pyc:decorator-gen-40>", line 2, in _answerButtons
  File "lib\site-packages\anki\hooks.py", line 666, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 658, in repl
  File "C:\Users\user\PortableApps\AnkiPortable\Anki2\addons21\1150874988\reviewer.py", line 122, in answerButtons
    buf += but(ease, label)
  File "C:\Users\user\PortableApps\AnkiPortable\Anki2\addons21\1150874988\reviewer.py", line 112, in but
    color,
UnboundLocalError: local variable 'color' referenced before assignment
```

Would it be feasible to combine _Beautify_ with _rememorize_btn_ or both of the add-ons I used?

**Comment by ShoroukAziz** [comment]
Thanks for letting me know. I will seriously consider making it compatible.

**Comment by PhongTong** [comment]
I have the same problem with other addon: https://ankiweb.net/shared/info/2494384865

**Comment by ShoroukAziz** [comment]
Hi, This addon colorizes the answer buttons which are already colorized in Beautify Anki. So you need to disable it if you still wanna use the addon

**Comment by ShoroukAziz** [comment]
Hi @galantra 
An option has been added to turn off Beautify's answer buttons customization 
if you set this option to false
 ``` 
 "change answer buttons": false,
```
You'll be able to use your addons again.
This has not yet been officially published on Ankiweb. However,
you can use it right now by downloading the source code from Github. or you can wait for the official update which shouldn't take long.
