### ISSUE TITLE
Items don't display properly. (or how could they be fixed?)

### ISSUE THREAD

**Issue by GoldEEr17** [my-Anki/Beautify-Anki#64]
Instead of showing the stats (Average, minutes more, due...) on the rights it writes them at the bottom and the decks on the top. Making Beautify Anki weirdly unbeautiful here. Anki also loads up with an error message (using 2.1.49 version even with no other add-ons. see the error message below).
Animations don't seem to work on the main page also. It's all a bit glitchy/weird.

Screenshots of the weird UI : 
https://prnt.sc/xw5Bd0_iAz1o
https://prnt.sc/JkFnsG3jGCKX

```
    
    Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-06-28 22:16:39
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['Beautify_Anki', 0, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AnkiConnect ['2055492159', 2022-05-15T18:09, 'None', '']
    CrowdAnki JSON exportimport Edit history Collaborate on deck creation ['1788670778', 2021-12-19T01:21, 'None', '']
    Edit Field During Review Cloze ['385888438', 2022-02-22T06:35, '6.11', mod]
    Image Occlusion Enhanced ['1374772155', 2020-04-28T04:21, 'None', '']
    Review Heatmap ['review_heatmap', 2021-06-03T15:56, 'None', '']

```

When I load Anki (having enabled only Beautify_Anki) I get this error message :
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-06-28 22:16:39

Traceback (most recent call last):
  File "aqt\main.py", line 523, in loadCollection
  File "aqt\main.py", line 672, in moveToState
  File "aqt\main.py", line 679, in _deckBrowserState
  File "aqt\deckbrowser.py", line 68, in show
  File "aqt\deckbrowser.py", line 143, in _renderPage
  File "aqt\deckbrowser.py", line 153, in __renderPage
  File "aqt\webview.py", line 472, in stdHtml
  File "aqt\hooks_gen.py", line 4099, in __call__
  File "C:\Users\leo\AppData\Roaming\Anki2\addons21\Beautify_Anki\__init__.py", line 80, in on_webview_will_set_content
    web_content.css.remove("deckbrowser.css")
ValueError: list.remove(x): x not in list
```

**Comment by ElenaPIR23** [comment]
Hello! It happens the same to me too
I would like to know if you have any solution :) 

Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-08 10:35:53

Traceback (most recent call last):
  File "aqt\main.py", line 523, in loadCollection
  File "aqt\main.py", line 672, in moveToState
  File "aqt\main.py", line 679, in _deckBrowserState
  File "aqt\deckbrowser.py", line 68, in show
  File "aqt\deckbrowser.py", line 143, in _renderPage
  File "aqt\deckbrowser.py", line 153, in __renderPage
  File "aqt\webview.py", line 472, in stdHtml
  File "aqt\hooks_gen.py", line 4099, in __call__
  File "C:\Users\elena\AppData\Roaming\Anki2\addons21\bonito\__init__.py", line 80, in on_webview_will_set_content
    web_content.css.remove("css/deckbrowser.css")
ValueError: list.remove(x): x not in list

**Comment by Rosalba02** [comment]
Hi ! I have the same problem, did you find a solution please ?

**Comment by Rosalba02** [comment]
> Instead of showing the stats (Average, minutes more, due...) on the rights it writes them at the bottom and the decks on the top. Making Beautify Anki weirdly unbeautiful here. Anki also loads up with an error message (using 2.1.49 version even with no other add-ons. see the error message below). Animations don't seem to work on the main page also. It's all a bit glitchy/weird.
> 
> Screenshots of the weird UI : https://prnt.sc/xw5Bd0_iAz1o https://prnt.sc/JkFnsG3jGCKX
> 
> ```
>     
>     Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
>     Platform: Windows 10
>     Flags: frz=True ao=True sv=2
>     Add-ons, last update check: 2022-06-28 22:16:39
>     
>     
>     ===Add-ons (active)===
>     (add-on provided name [Add-on folder, installed at, version, is config changed])
>     '' ['Beautify_Anki', 0, 'None', mod]
>     
>     ===IDs of active AnkiWeb add-ons===
>     
>     
>     ===Add-ons (inactive)===
>     (add-on provided name [Add-on folder, installed at, version, is config changed])
>     AnkiConnect ['2055492159', 2022-05-15T18:09, 'None', '']
>     CrowdAnki JSON exportimport Edit history Collaborate on deck creation ['1788670778', 2021-12-19T01:21, 'None', '']
>     Edit Field During Review Cloze ['385888438', 2022-02-22T06:35, '6.11', mod]
>     Image Occlusion Enhanced ['1374772155', 2020-04-28T04:21, 'None', '']
>     Review Heatmap ['review_heatmap', 2021-06-03T15:56, 'None', '']
> ```
> 
> When I load Anki (having enabled only Beautify_Anki) I get this error message :
> 
> ```
> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
> Debug info:
> Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
> Platform: Windows 10
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2022-06-28 22:16:39
> 
> Traceback (most recent call last):
>   File "aqt\main.py", line 523, in loadCollection
>   File "aqt\main.py", line 672, in moveToState
>   File "aqt\main.py", line 679, in _deckBrowserState
>   File "aqt\deckbrowser.py", line 68, in show
>   File "aqt\deckbrowser.py", line 143, in _renderPage
>   File "aqt\deckbrowser.py", line 153, in __renderPage
>   File "aqt\webview.py", line 472, in stdHtml
>   File "aqt\hooks_gen.py", line 4099, in __call__
>   File "C:\Users\leo\AppData\Roaming\Anki2\addons21\Beautify_Anki\__init__.py", line 80, in on_webview_will_set_content
>     web_content.css.remove("deckbrowser.css")
> ValueError: list.remove(x): x not in list
> ```

Hi ! I have the same issue, did you find a solution please ?

**Comment by Rosalba02** [comment]
@GoldEEr17 @ElenaPIR23 
 Hi ! I have the same issue, did you find a solution please ?

**Comment by GoldEEr17** [comment]
Yes I did. I downloaded a more recent version that doesn't have this issue because apparently the ankiweb page doesn't really feature the latest one and it's kind of glitched.

Here is a post I made on that ankiweb as a tutorial on how to download beautify anki (with the correct link to use to download it, so it should be working with this now, at least I can tell you that it's working on my 2.1.49 anki version)

HERE IS HOW TO INSTALL FOR LATEST 2.1.49 VERSION

Thanks to fylux's patch, Beautify Anki IS compatible with current latest version (July 6th 2022 on 2.1.49).



How to install it :

1) Open Anki and press Ctrl+Shift+A or simply open add-on preferences from Tools menu.
2) After the add-on preferences window is open click on the 'View Files' button. A folder will open. Then exit Anki.
OR simply
Go to < C:\Users\<username>\AppData\Roaming\Anki2\addons21\ > or the directory where Anki keeps your add-ons
3) Download the latest version of Beautify Anki from the GitHub Page ( https://github.com/ShoroukAziz/Beautify-Anki/releases ). It currently is "V.0.3.3.zip" of 16 Jan 2022 (compatible with 2.1.49)
4) Open the .zip file, and rename the "V.0.3.3" folder to something else (like: Beautify_Anki) (it's important or it won't work because of the dots in the folder name).
5) Copy the folder you just renamed and paste it into the addons folder you just opened in step2.
6) Again open the Anki Add-ons menu by pressing Ctrl+Shift+A or look in the Tools menu.
7) Beautify_Anki (or whatever name you used for the folder) should appear in the list. Select this and click on 'Toggle Enable'.
8) Restart Anki. Voila! You just updated Beautify Anki.
